# Generated by Django 4.1.5 on 2023-02-10 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_relation',
            new_name='Cart',
        ),
    ]
