# Generated by Django 4.1.5 on 2023-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_relation_remove_product_for_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Указывать в граммах', verbose_name='Вес товара'),
        ),
    ]
