# Generated by Django 4.1.5 on 2023-02-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshots',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='main.product', verbose_name='Товар'),
        ),
    ]
