# Generated by Django 4.1.5 on 2023-02-22 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_productshots_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='common_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(default='Фамилия по умолчанию', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Имя по умолчанию', max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(default='Отчество по умолчанию', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Не задан', max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='Индекс по умолчанию', max_length=50, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='Адрес по умолчанию', max_length=400, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.CharField(default='0', max_length=30, verbose_name='Трек номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('a', 'Обрабатывается'), ('b', 'Передано в доставку'), ('c', 'Доставлено')], default='a', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productshots',
            name='name',
            field=models.CharField(help_text='Если картинка по какой-то причине не загрузится, то выводится этот текст', max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Order_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('order_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_relations', to='main.order', verbose_name='Пакет товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товар для заказа',
                'verbose_name_plural': 'Товары для заказа',
            },
        ),
    ]
