# Generated by Django 4.1.5 on 2023-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_products_order_common_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Трек номер'),
        ),
    ]
