# Generated by Django 4.1.5 on 2023-02-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новый'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment ID'),
        ),
    ]
