# Generated by Django 4.1.5 on 2023-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_new_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество в складе'),
        ),
    ]
